train_dataset: mini-imagenet
train_dataset_args: {split: train}
tval_dataset: mini-imagenet
tval_dataset_args: {split: test}
val_dataset: mini-imagenet
val_dataset_args: {split: val}

model: meta-baseline
model_args: 
    encoder: resnet12-wide-att
    encoder_args: {}
    method: dbrn_bias
    neighbor_k: 5
# load_encoder: ./save/classifier_mini-imagenet_resnet12/epoch-last.pth
load_encoder: ./save/classifier_mini-imagenet_resnet12-wide-att-avgpool-linear-classifier/epoch-last.pth

n_way: 5
n_shot: 5
n_query: 15
train_batches: 200
ep_per_batch: 4

max_epoch: 20
optimizer: sgd # adam-stand # sgd
optimizer_args: {lr: 0.001, weight_decay: 5.e-4}

visualize_datasets: True


#--------添加的-------#
num_workers: 2
pin_memory : false
#---------end---------#
