train_dataset: mini-imagenet
train_dataset_args: {split: train, augment: resize}
val_dataset: mini-imagenet
val_dataset_args: {split: train_phase_val}
fs_dataset: mini-imagenet
fs_dataset_args: {split: test}
eval_fs_epoch: 1

model: classifier
model_args:
    encoder: resnet12-wide-att
    encoder_args: {}
    classifier: avgpool-linear-classifier
    classifier_args: {n_classes: 64}

batch_size: 128
max_epoch: 1 # 100
optimizer:  sgd # adam-stand # sgd  
optimizer_args: {lr: 0.1, weight_decay: 5.e-4, milestones: [90]}

save_epoch: 1
visualize_datasets: true

#--------添加的-------#
num_workers: 2
pin_memory : false
beta: 0.2 # 这个不改
cutmix_prob: 1.0 # 0.5 #试试全都mix # cutmix_prob=0.5 is used for CIFAR experiments, otherwise, we set cutmix_prob=1.0 including ImageNet experiments.
fs_model_args:
    encoder: resnet12-wide-att
    encoder_args: {}
    method: M2L_Wass #KLcos
    num_classes: 5
    neighbor_k: 3
    batch_size: 4
    shot_num: 1
ep_per_batch: 4
#---------end---------#

# 修改的部分 eval_fs_epoch: 1 save_epoch: 1 
# 共2个