dataset: mini-imagenet
dataset_args: {split: test}

load: ./save/MODEL_FOLDER/EPOCH_X.pth

# Replace load with load_encoder for loading the encoder only (e.g. for testing Classifier-Baseline)

#--------添加的-------#
num_workers: 2
pin_memory : false
#---------end---------#